### ISSUE TITLE
Setting CLEARML_SERVER_SUB_PATH in webserver.extraEnvs doesn't work

### ISSUE THREAD

**Issue by sruangwan** [allegroai/clearml-helm-charts#101]
Hello,

I want to set up ClearML server that uses sub path (URL prefix) and I found that it's supported since clearml-server v1.4.0 (https://github.com/allegroai/clearml-server/pull/121). Supposedly, when I set `CLEARML_SERVER_SUB_PATH` in `webserver.extraEnvs`, it should activate [this](https://github.com/allegroai/clearml-server/blob/master/docker/build/internal_files/entrypoint.sh#L53-L59) if block in the clearml-server's entrypoint and replace href and env.js templates. However, it doesn't work for me. I inspected page source and my base href is still `/` so the web app assets can't be accessed correctly. 

For instance, I checked [env.js](https://github.com/allegroai/clearml-web/blob/master/src/env.js) on my web app and found that the template wasn't replaced correctly too. It's still show `window.__env.subPath = '${CLEARML_SERVER_SUB_PATH}';`

#### Steps to reproduce
values.yaml
```yaml
webserver:
  extraEnvs:
    - name: CLEARML_SERVER_SUB_PATH
      value: "clearml"
```
```
helm install clearml allegroai/clearml -f values.yaml
```

I'm fairly new to Helm charts so I'm not sure if this problem is on my side. Please let me know if that's the case.
Thanks.

**Comment by jkhenning** [comment]
Hi @sruangwan , there's currently an issue with this feature, and we're working on it. In general, this should also be configured in the apiserver section since it affects it as well. We'll update when this is resolved.

**Comment by shyallegro** [comment]
related to https://github.com/allegroai/clearml-server/issues/135

**Comment by pollfly** [comment]
Hey @sruangwan! [v1.7.0](https://github.com/allegroai/clearml-server/releases/tag/v1.7.0) is now out supporting serving the UI from a non-root path of the ClearML Server.

**Comment by sruangwan** [comment]
Hi @pollfly, thanks for the good news!
