### ISSUE TITLE
Allow adding pod volumes and container volumeMounts

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#102]
Hello.

At the moment it is not possible to add additional volumes and volumeMounts via values. This should be implemented for all the pods including the clearml agent and its spawns.

My specific use case is to enable using the [Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html) to sync AWS Parameter Store into k8s secrets.

**Comment by jkhenning** [comment]
@valeriano-manassero any thoughts?

**Comment by valeriano-manassero** [comment]
Probably we should add volumeMounts to podTemplate and glue agent pod from what I can see.

**Comment by andreimahu** [comment]
I can make a PR for this if you can't take it.
