### ISSUE TITLE
Agent spawned task pods S3 storage and annotations

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#103]
How would I go about configuring the spawned task pods to use S3 as artifact storage?

Do these pods inherit the clearmlConfig from the glue agent? If they do then I will just add the s3 config to the values.

Another issue would be that these task pods don't seems to have a k8s service account. A service account that can be annotated is required in order to gain the ability to associate an AWS IAM ROLE to the pod and hence provide permissions for S3.

I would also like the ability to add annotations to the spawned pods. My specific use case for this is disabling istio sidecar injection as it seems to prevent the pod from being terminated.

**Comment by jkhenning** [comment]
Hi @andreimahu , 

> How would I go about configuring the spawned task pods to use S3 as artifact storage?
>Do these pods inherit the clearmlConfig from the glue agent? If they do then I will just add the s3 config to the values.

You can simply use the `clearmlConfig` section here: https://github.com/allegroai/clearml-helm-charts/blob/19a6785a03b780c2d22da1e79bcd69ac9ffcd839/charts/clearml-agent/values.yaml#L28
This configuration is mounted as a configuration file for every pod spawned by the k8s glue agent.

> Another issue would be that these task pods don't seems to have a k8s service account. A service > account that can be annotated is required in order to gain the ability to associate an AWS IAM ROLE to the pod and hence provide permissions for S3.

@valeriano-manassero any thought?

> I would also like the ability to add annotations to the spawned pods. My specific use case for this is disabling istio sidecar injection as it seems to prevent the pod from being terminated.

I think you can do that very easily by modifying the pod template here: https://github.com/allegroai/clearml-helm-charts/blob/19a6785a03b780c2d22da1e79bcd69ac9ffcd839/charts/clearml-agent/values.yaml#L70

**Comment by valeriano-manassero** [comment]
S3 is a config that is mounted by `clearmlConfig` value so it should be enough to specify it there.

**Comment by andreimahu** [comment]
Thank you for the reply. Configuring the s3 is clear now. The other 2 issues still remain.

1. The need for a service account which can be annotated for the spawned pods.
2. Based on the template agentk8sglue-configmap.yaml does use only specific parts of the "podTemplate: " from values. A section for metadata annotations must be added to the template.
