### ISSUE TITLE
agentk8sglue-configmap existing secret name is not correct

### ISSUE THREAD

**Issue by safwanp314** [allegroai/clearml-helm-charts#105]
Curly brackets are missing for .Values.imageCredentials.existingSecret

[agentk8sglue-configmap](https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-agent/templates/agentk8sglue-configmap.yaml#L14)

**Comment by jkhenning** [comment]
Fixed in https://github.com/allegroai/clearml-helm-charts/pull/107
