### ISSUE TITLE
ClearML serving auto-scaling strategy

### ISSUE THREAD

**Issue by senysenyseny16** [allegroai/clearml-helm-charts#110]
Hello, ClearML team!

I'm trying to understand how serving auto-scaling works.

From readme:

    Scalable
    Multi model per container
    Multi models per serving service
    Multi-service support (fully seperated multiple serving service running independently)
    Multi cluster support
    Out-of-the-box node auto-scaling based on load/usage <---- *

I found that serving has ability to auto-scale, but in helm charts ([triton](https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-serving/templates/clearml-serving-triton-deployment.yaml) for example) I only found replicas: 1 and didn't find an auto-scale implementation anywhere (like this https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/, for example).

Could you please clarify Clearml-serving scaling strategy and where can I find configuration files?

Thanks in advance.

**Comment by jkhenning** [comment]
Hi @senysenyseny16, 

Apologies for missing this 🙁

@valeriano-manassero WDYT?

**Comment by valeriano-manassero** [comment]
Actually serving chart doesn't support autoscaling.
Referenced issue https://github.com/allegroai/clearml-serving/issues/34 has a good answer but it's not possible to apply these configs without having an HPA definition.

I'm going to check about an implementation when possible about this.

**Comment by senysenyseny16** [comment]
@valeriano-manassero @thepycoder

thanks for your reply, it works as expected with HPA.
