### ISSUE TITLE
A comment exists that appears to be incorrect.

### ISSUE THREAD

**Issue by kex5n** [allegroai/clearml-helm-charts#111]
Hi, ClearML team.

I found comments that seems incorrect in `clearml-helm-charts/charts/clearml/values.yaml`.

All comments in this block say "if elasticsearch.enabled is false".
https://github.com/allegroai/clearml-helm-charts/blob/6aea682b0d1c1952bd2138e2dd0ffe18b47bd019/charts/clearml/values.yaml#L232-L238

However, I think "if mongod.enabled is false" and "if redis.enabled is false" are correct, respectively.

**Comment by valeriano-manassero** [comment]
Yes, you are right, I will fix it on next implementation to publish, ty for pointing me there!
