### ISSUE TITLE
Add nodeSelector to the agentk8sglue pod

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#115]
Hello. This functionality seems to be missing at the moment. It is possible to set nodeSelector for the pods that are spawned by the agent but not for the agent itself. 

https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-agent/templates/agentk8sglue-deployment.yaml

**Comment by valeriano-manassero** [comment]
I'm working on a new chart version, will try to include this.
