### ISSUE TITLE
Add imagePullPolicy to agent and pods spawned by the agent

### ISSUE THREAD

**Issue by andreimahu** [allegroai/clearml-helm-charts#117]
Hello

At the moment `imagePullPolicy` for the k8s glue agent is not customizable via values and defaults to `IfNotPresent`.

The template for the spawned worker pods is missing `imagePullPolicy` completely so it would be nice to have it added.

Thank you.

**Comment by valeriano-manassero** [comment]
Will check and try to add this option during refactoring process I'm working on for next major release.
