### ISSUE TITLE
Old pull request overrided 

### ISSUE THREAD

**Issue by zandolsi-psee** [allegroai/clearml-helm-charts#128]
Hi,

I have pushed a pull request to allow using secret as config for the api server (espcially for defined user to avoid plain text password in git source code). This [PR](https://github.com/allegroai/clearml-helm-charts/pull/95) was merged. But this update is deleted and no more present in the main branch.
Any idea about this ? Is there any way to define user without using configmap ?

Regards,

**Comment by valeriano-manassero** [comment]
Hi @zandolsi-psee , I'm sorry for this regression, I'm going to include again your functionality in next release. I planned patch release for next week.
