### ISSUE TITLE
Error <$.Values.agentk8sglue.labels>: nil pointer evaluating interface {}.labels

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#152]
I am trying to install ClearML umbrella with this sub charts:
**1. clearml:5.6.0
2. clearml-agent-3.3.1**

when I am trying to install it I am getting this error:

**Error: template: dc-allegro/charts/clearml/templates/webserver-service.yaml:7:8: executing "dc-allegro/charts/clearml/templates/webserver-service.yaml" at <include "clearml.labels" .>: error calling include: template: dc-allegro/charts/clearml-agent/templates/_helpers.tpl:25:8: executing "clearml.labels" at <$.Values.agentk8sglue.labels>: nil pointer evaluating interface {}.labels**

when I am trying to install each of the sub chart separately this work but together isn’t 

After investigation I saw this lines in  https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-agent/templates/_helpers.tpl

{{- if $.Values.agentk8sglue.labels }}
{{ toYaml $.Values.agentk8sglue.labels }}

when I remove those lines this work

I saw that this line was added in 3.1.0
before this in 3.0.0 the umbrella working well with both

So seems like those line are breaking something please check this  this 

references: 
https://github.com/allegroai/clearml-helm-charts/commit/622ec331acbd63ad596a24504ed1c383bb227533

**Comment by awaizman1** [comment]
The root cause for this error is that both charts _helpers.tpl use the same variables names (i.e. ```{{- define "clearml.name" -}}```). The way helm works, causes it to take the last definition.

from [helm doc](https://helm.sh/docs/chart_template_guide/named_templates/)
> An important detail to keep in mind when naming templates: template names are global. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.

> One popular naming convention is to prefix each defined template with the name of the chart: {{ define "mychart.labels" }}. By using the specific chart name as a prefix we can avoid any conflicts that may arise due to two different charts that implement templates of the same name.

community best practice is to define all variables in _helpers.tpl using the chart name (which is unique), so I think the fix here should be fixing clearml-agent _helpers.tpl to define variables using ```clearml-agent.``` prefix.

once this fixed we can use both charts under same umbrella

**Comment by valeriano-manassero** [comment]
Ty for reporting this, I'm going to work on it soon.
