### ISSUE TITLE
Repo endpoint is missing (404)

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml-helm-charts#155]
The repo endpoint, as given in the main README, is https://allegroai.github.io/clearml-helm-charts, which is missing:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/12184618/218394984-e663c2bb-f7cf-4c79-9d3d-19957bb8fe2f.png">

Which in turn causes helm to complain :(
```
fatal: [localhost]: FAILED! => changed=false 
  command: /usr/sbin/helm repo update
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout:
    stderr: Error: no repositories found. You must add one before updating
  stderr: |-
    Error: no repositories found. You must add one before updating
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by valeriano-manassero** [comment]
Hi,
I'm a bit confused, README is not needed for helm repo afaik, I just tried it:
```
❯ helm repo update allegroai
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "allegroai" chart repository
Update Complete. ⎈Happy Helming!⎈
```
Helm should use https://allegroai.github.io/clearml-helm-charts/index.yaml 

Can you pls retry eventually with `--debug` flag to understand better what is the problem?

**Comment by valeriano-manassero** [comment]
Ok, after further checks it looks we are good from repo standpoint. It was an issue on client side.
