### ISSUE TITLE
fileserver doesn’t have an option to be with ephemeral storage 

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#160]
it seems like that fileserver doesn’t have an option to be with ephemeral storage 
as ES and Mongo have
we must have this if we want to install this as a temporary quickly deployment

**Comment by valeriano-manassero** [comment]
Are you referring to `empryDir` in fileserver deployment instead of a PVC?

**Comment by joebatish** [comment]
i think yes 
the main idea here is to be without any pvc associated with
