### ISSUE TITLE
After Changing the templateOverride on the Glue Chart Need To Restart Manually 

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#163]
i have noticed that after i have changed the  templateOverride on the Glue Chart 
and i have upgrade the chart
Need To Restart Manually the pod/deployment  for changes to take effect

**Comment by valeriano-manassero** [comment]
Ty for this: checksum of the entire template cm need to be added to force pod recreation. I'm going to add it soon with a release.

**Comment by valeriano-manassero** [comment]
Fixed in latest agent chart release 3.4.0.
