### ISSUE TITLE
[clearml-agent] priorityClassName in pod template

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#165]
**templateOverrides:**

 do we have an option to override setting on the pod level and not on the container level  only ?
 if for example i want to have specific pod setting  for queue A and specific pod setting for queue B
 
 now i can have only container setting for queue A and container setting  for queue B
 
 this is very important to have this

**Comment by valeriano-manassero** [comment]
On Enterprise version, each single value defined in `basePodTemplate` is overridable in queue `templateOverrides`  section.
Can you pls post an example of what you need to override so I can check?
Thanks.

**Comment by joebatish** [comment]
sure the highly important thing that need in gpu management is prioritization 
so i want to be able to have priority for each queue 
i can reach this in PriorityClass definition
**but this is in the pod level only** 
so at the basic i think that this is must to have this per glue general template
because ew don't want other "**non glue pods**" to take control over all our gpus that located on the same node 
(**in case that we have other allocation on the same node**)
but this will be amazing if we can do this as a per queue

**Comment by valeriano-manassero** [comment]
So adding `priorityClassName` in configurable options in `basePodTemplate` (and related overridable queue section should be enough?

**Comment by joebatish** [comment]
adding priorityClassName in configurable options in basePodTemplate this will give u the ability to have priority to all our 
tasks regardless of the queue kind of pods
but for the beginning this is ok .

after this it will be amazing to give us the ability to priority the pods of each queue that we have under 
 **templateOverrides**
 
 for example 
      g-2:
        templateOverrides:
          resources:
            limits:
              nvidia.com/gpu: 2
              memory: 16G
            requests:
              nvidia.com/gpu: 2
          **priorityClassName: priority2**  

      g-1:
        templateOverrides:
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 12G
            requests:
                nvidia.com/gpu: 1
          **priorityClassName: priority1**
