### ISSUE TITLE
ClearML external mongoDB 

### ISSUE THREAD

**Issue by joebatish** [allegroai/clearml-helm-charts#173]
mongodbConnectionStringAuth: ""
mongodbConnectionStringBackend: "mongodb://host:27017"
i have got this error

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 63fdf5c11a8f9c78f7e8e403, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>

**Comment by valeriano-manassero** [comment]
Hi,
both `mongodbConnectionStringAuth` and `mongodbConnectionStringBackend` must be valid in case of external mongodb usage pointing to Auth and Backend db with something like `mongodb://dbhostname:27017/authdb`.

**Comment by joebatish** [comment]
can u please give an example ?

i dont have auth enable on the mongo 
have an  clean mongoDB

**Comment by valeriano-manassero** [comment]
Creating the right string for external MongoDB depends on configuration on it and not ClearML chart.
Previous example was without authentication on MongoDB but still both mongodbConnectionStringAuth and mongodbConnectionStringBackend must be valid pointing to ClearML auth db and ClearML backend DB. Usually these values are included in config url by Mongo as dbname.

As you can see here: https://www.mongodb.com/docs/manual/reference/connection-string/ there are a lot of combinations depending on how you created your MongoDB setup.

**Comment by joebatish** [comment]
but i sont understatnd somthing 

i can connect to the db 

] Registering connection to auth-db (mongodb://1.1.1.1:27017/authdb)
[2023-02-28 13:02:31,585] [66] [INFO] [clearml.database] Registering connection to backend-db (mongodb://1.1.1.1:27017)


Failed creating fixed user clearml: The fields "{'companies', 'read_only', 'providers', 'credentials', 'sec_groups', 'block_user_login', 'role', 'permissions', 'email'}" do not exist on the document "User"
[2023-02-28 13:02:31,744] [66] [INFO] [clearml.__init__] Creating apps user: Apps user

**Comment by valeriano-manassero** [comment]
I'm not totally sure on application level so I will wait for @jkhenning to chime in but, in the meanwhile if you set
`mongodbConnectionStringAuth: "mongodb://1.1.1.1:27017/authdb"`
I can imagine you also set:
`mongodbConnectionStringBackend: "mongodb://1.1.1.1:27017/backenddb"`

is that the case?

**Comment by joebatish** [comment]
ok this is what i wanted from u 


i missed this 
/auth

thanks mate

**Comment by joebatish** [comment]
thanks !
issue resolved
