### ISSUE TITLE
Is there a guide / example for setting the clearml-server conf files when using helm?

### ISSUE THREAD

**Issue by blair-anson** [allegroai/clearml-helm-charts#174]
I am looking into how to add web authentication and other server config. Is there an example of how to set these conf files when using helm?

https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_config/#web-login-authentication

**Comment by valeriano-manassero** [comment]
Hi,
as you can see in `values.yaml` we have `additionalConfigs` section that can be created using configurations files automatically mounted into apiserver pod as config files.

**Comment by blair-anson** [comment]
Thanks, I was looking at the `values-production.yaml` file but should have checked the other one as well.
