### ISSUE TITLE
apiserver's init container waits forever pinging a MongoDB service that does not exist

### ISSUE THREAD

**Issue by alexeiaguiar** [allegroai/clearml-helm-charts#177]
I installed the last version of the ClearML chart (5.8.0) and the pod clearml-apiserver stays in the pending state forever. I saw that there is an init container that waits for Elasticsearch, MongoDB and Redis. It uses curl to verify if the MongoDB service is up, but it uses a service name that does not exist. Here is the script of the init container in execution:
`while [ $(curl --telnet-option BOGUS --connect-timeout 2 -s
          "telnet://clearml-mongodb:27017" -o /dev/null; echo $?) -ne 49 ] ; do
            echo "waiting for mongodb" ;
            sleep 5 ;
          done ;`
The service "clearml-mongodb" doesn't exist. What I see for MongoDB is the service "clearml-mongodb-headless". If I change the script and put "clearml-mongodb-headless", it works and all the pods go to the state "running".

This is the line on the init container's script:
https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/templates/apiserver-deployment.yaml#L64

**Comment by valeriano-manassero** [comment]
Are you overriding any value? If yes can you pls post override file used here?

**Comment by alexeiaguiar** [comment]
Yes. This is the file:

`apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "api-clearml.icentia.net"
    tlsSecretName: clearml-cert
fileserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "files-clearml.icentia.net"
    tlsSecretName: clearml-cert
webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "clearml.icentia.net"
    tlsSecretName: clearml-cert
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
redis:
  master:
    name: "{{ .Release.Name }}-redis"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
      storageClass: null
  slave:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
      storageClass: null
  cluster:
    enabled: true
  sentinel:
    enabled: true
mongodb:
  enabled: true
  architecture: replicaset
  replicaCount: 2
  arbiter:
    enabled: true
  pdb:
    create: true
  podAntiAffinityPreset: soft
elasticsearch:
  replicas: 2`

**Comment by alexeiaguiar** [comment]
I used these commands:
```shell
helm repo add allegroai https://allegroai.github.io/clearml-helm-charts
helm -n clearml install clearml allegroai/clearml -f values-production.yaml
```

**Comment by valeriano-manassero** [comment]
Pls try ClearML chart 5.8.1 that should fix issue you experienced.
Let me know if it's ok!

**Comment by alexeiaguiar** [comment]
Indeed, it's working now. Thanks you!
