### ISSUE TITLE
Add configureable annotations for services

### ISSUE THREAD

**Issue by alexpusch** [allegroai/clearml-helm-charts#183]
In some case, in GKE in particular the Service resource is expected to contain annotations for GKE to provision a load balancer for the service - An example can be seen here - https://cloud.google.com/kubernetes-engine/docs/concepts/ingress.

Current helm values do not provide a configureable way to change service annotations.

**Comment by valeriano-manassero** [comment]
Hi,
any kind of annotation is possible for each single ingress rule:
https://github.com/allegroai/clearml-helm-charts/blob/e4f9cbfe8ef10660b3c97095a815f8142eac2a88/charts/clearml/values.yaml#L78
https://github.com/allegroai/clearml-helm-charts/blob/e4f9cbfe8ef10660b3c97095a815f8142eac2a88/charts/clearml/values.yaml#L182
https://github.com/allegroai/clearml-helm-charts/blob/e4f9cbfe8ef10660b3c97095a815f8142eac2a88/charts/clearml/values.yaml#L250

Is this what you need?

**Comment by alexpusch** [comment]
@valeriano-manassero thanks for the answer. I actually need to add annotation to the `service` resource and not just the `ingress`. for example - [here ](https://github.com/allegroai/clearml-helm-charts/blob/e4f9cbfe8ef10660b3c97095a815f8142eac2a88/charts/clearml/templates/webserver-service.yaml#L5)
