### ISSUE TITLE
apiserver's init container waits forever pinging a redis service that does not exist

### ISSUE THREAD

**Issue by TouhKa** [allegroai/clearml-helm-charts#205]
Hello there, 
with the latest version (6.1.1) of the production setting of the clearml server, there is the same issue as in #177 but for the redis service, which results in an endless loop.
While the script (https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/templates/apiserver-deployment.yaml#L70) expects a service `clearml-redis`, the actual service is called `clearml-redis-headless`.

**Comment by valeriano-manassero** [comment]
Hi @TouhKa , can you pls test ClearML chart version 7.0.1 and let me know?

**Comment by TouhKa** [comment]
@valeriano-manassero, with version 7.0.1 the api server now starts correctly.
