### ISSUE TITLE
Wrong usage of EXTRA_PYTHON_PACKAGES environment variable

### ISSUE THREAD

**Issue by imadassamani** [allegroai/clearml-helm-charts#210]
The deployment of inference serving is using the wrong environment variable which is EXTRA_PYTHON_PACKAGES, but the clearml-serving source code is reading env from CLEARML_EXTRA_PYTHON_PACKAGES.

**Comment by valeriano-manassero** [comment]
Nice catch, ty!

PR incoming 😄
