### ISSUE TITLE
Clearml Helm Deployment

### ISSUE THREAD

**Issue by abfshaal** [allegroai/clearml-helm-charts#211]
## Proposal Summary
With clearml helm deployment, I realised it forces sticking to the naming convention of app. or api. for the ingress routes, 
Is there any environment variable that would allow me to specify the ingress route for the api without having to stick to app. naming? 

When i try to do app- it gets stuck trying to call the api with the same ingress as the app 

## Motivation
certificate issues when deploying on a kubernetes cluster with https

**Comment by valeriano-manassero** [comment]
You can define any ingress hostname you want for these services simply overriding `hostName` for each single service. Ofc you need 3 different hostnames to make it works since they are separated services. If generating certificates for 4th level domain is an issue, you can set something like app-clear.<domain> staying on 3rd level domain.

About https, not setting `tlsSecretName` will produce Http only ingress rules.

**Comment by abfshaal** [comment]
I have tried that, 
for example, I tried to change the 3 ingresses to 
api-domanname (instead of api.domainname)
app-domainname(instead of app.domainname)
fileserver-domainname(instead of fileserver.domainname)

This resulted in the webserver app trying to call app-domainname instead of api-domainname 
My guess was that there is some string replacement happening inside clearml to handle the communication.
And when I re read the docs, it seemed that it is mentioned to keep the api/fileserver/app.domainname

I tried tweaking the environment variables aswell of the NGINX for the webapp, to no luck. 
Maybe it is there by design? if so are they any intentions to changing this behavior to allow for more flexibility with self hosted deployments and namings?

**Comment by valeriano-manassero** [comment]
There is something not clear to me in this process.

App server connect to api server using internal k8s svc so egresses are not involved here.

It would help a lot if you can attache full override file you are using so I can try to reproduce issue, thanks.

**Comment by abfshaal** [comment]
`apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "api-<DOMAIN>"
fileserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "files-<DOMAIN>"
webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "app-<DOMAIN>"
redis:
  master:
    name: "{{ .Release.Name }}-redis"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
      storageClass: null
  slave:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
      storageClass: null
  architecture: replication

mongodb:
  enabled: true
  architecture: replicaset
  replicaCount: 3
  arbiter:
    enabled: false
  pdb:
    create: true
  podAntiAffinityPreset: soft
elasticsearch:
  replicas: 3
`
Apologies for my late reply, this is the the edit I have introduced in to the values-production.yaml. When I deploy my clearml helm charts in this way, the communication between the app and the api stops from working

**Comment by valeriano-manassero** [comment]
Will try to reproduce in next days and let you know. Thanks

**Comment by abfshaal** [comment]
I also have another question, 
When I finish the deployment, I get another error which says 
Traceback (most recent call last):
  File "/opt/clearml/apiserver/service_repo/service_repo.py", line 288, in handle_call
    ret = endpoint.func(call, company, call.data_model)
  File "/opt/clearml/apiserver/services/organization.py", line 27, in get_tags
    company, entity, include_system=request.include_system, filter_=filter_dict,
File "/opt/clearml/apiserver/bll/organization/__init__.py", line 36, in get_tags
    company_id, include_system=include_system, filter_=filter_
  File "/opt/clearml/apiserver/bll/organization/tags_cache.py", line 103, in get_tags
    self.redis.rpush(redis_key, self._dummy_tag, *tags)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2016, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response

redis.exceptions.ReadOnlyError: You can't write against a read only replica.

How can I edit the redis replicas to allow for this write operation?

**Comment by abfshaal** [comment]
Update: I have managed to remove the salve architecture, but I am not sure if that is ideal for a clearml deployment, it seems to avoid the error of "readonly", I am sure there must be a better way to deal with this though

**Comment by valeriano-manassero** [comment]
I tested this config on a brand new k8s cluster and it looks good to me; ingress controllers does not impact communication between  pods because they use internal k8s svcs.

Moreover when you call api from web application, you still connect to web application itself, if you talk to api directly it means you are using sdk so maybe the issue can be on that side. Just guessing, I have no evidence atm.

**Comment by abfshaal** [comment]
You are right, after further looking in to it, the pod communication happens fine, they do not rely on ingresses, I had a misunderstanding on that part, apologies. 

I will try to rebuild the clearml with the different ingress name and let you know about. Many thanks for your replies!

**Comment by valeriano-manassero** [comment]
you are welcome, feel free to reopen issue if you get into troubles again.
