### ISSUE TITLE
Github IO missing versions

### ISSUE THREAD

**Issue by imadassamani** [allegroai/clearml-helm-charts#216]
This may sound a bit like a noob question, but i'm installing helm charts via the repo _https://allegroai.github.io/clearml-helm-charts_ , and seems like i can only get versions upto 0.7.0. Am i using the wrong repo url or is it just not updated?

**Comment by valeriano-manassero** [comment]
Hi,
what is output of `helm search repo allegroai` ?

After an `helm repo update` my search returns:

```
NAME                                         	CHART VERSION	APP VERSION	DESCRIPTION
allegroai/clearml                            	7.1.0        	1.11.0     	MLOps platform
allegroai/clearml-agent                      	5.0.1        	1.24       	MLOps platform Task running agent 
allegroai/clearml-serving                    	1.0.3        	1.2.0      	ClearML Serving Helm Chart
```

**Comment by imadassamani** [comment]
I think because i'm using an outdated rancher, the helm search repo command is returning error instead

**Comment by valeriano-manassero** [comment]
I guess we can close this, feel free to reopen if you have further questions on this topic.
