### ISSUE TITLE
Make ingress version configurable

### ISSUE THREAD

**Issue by matejkosco** [allegroai/clearml-helm-charts#23]
The Ingress apiVersion changed and probably will change again in future.

I'm getting the following error:
`W0903 17:39:02.765848    1234 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

Could you make the apiVersion cofigurable?

**Comment by jkhenning** [comment]
@valeriano-manassero WDYT?

**Comment by valeriano-manassero** [comment]
This should be a warning not preventing the chart to be installed. Anyway this should be improved selecting the api version based on cluster version; will try to work on it asap.

**Comment by valeriano-manassero** [comment]
@matejkosco Should be fixed in chart version 2.2.3
