### ISSUE TITLE
[allegroai/clearml] Elastic statefulset does not use a dedicated serviceAccount

### ISSUE THREAD

**Issue by thoraxe** [allegroai/clearml-helm-charts#246]
### Describe the bug a clear and concise description of what the bug is.

The Elastic StatefulSet does not declare a serviceAccount to use, which makes it difficult to constrain the blast radius on the privileged status it requires. Unfortunately, "you" are inheriting that chart from an upstream, so it's not really this repo's issue to fix, although it is something to be aware of.

### What's your helm version?

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v0.23.0", GitCommit:"7c299f197c583559613ae9cdeb01f58496437a29", GitTreeState:"clean", BuildDate:"2022-02-08T22:39:24Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+b404935", GitCommit:"9ded806a7d5deed41a20f680cf89dae58bbb5697", GitTreeState:"clean", BuildDate:"2023-04-19T02:20:48Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### What's the chart version?

7.3.0

### Enter the changed values of values.yaml?

NONE

**Comment by thoraxe** [comment]
Actually, it appears that the upstream ES chart you're using does support serviceAccount, it just isn't apparently defaulted to anything:
https://github.com/elastic/helm-charts/blob/v7.17.3/elasticsearch/templates/statefulset.yaml#L72-L74

Would you be willing to accept a PR that sets your default values to create and use an SA called `clearml-elastic`?

https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/values.yaml#L372-L382

**Comment by valeriano-manassero** [comment]
This can be a good idea, I just need to check what can happen if we define sa for an existing installation.

**Comment by valeriano-manassero** [comment]
After looking at it, I guess it's a matter of just adding:

```
elaticsearch:
  rbac:
    create: true
    serviceAccountName: "clearml-elastic"
```

this can be done by anyone wanting elastic to use specific sa, I'm still unsure if it's a good idea to set it by default.

**Comment by thoraxe** [comment]
@valeriano-manassero in the absence of specifying an SA for elastic, unless your cluster allows privileged access by default, elastic will fail to run.

From a security and blast-radius perspective, you want to minimize the number of things that can run with privileges.

Specifying an SA for elastic allows you to grant ONLY the Elastic SA to have privileged access and only in the namespace into which the chart is installed.

It's definitely a best practice.

**Comment by valeriano-manassero** [comment]
Tested on existing installation and it just restart pods after sa is created so it's a good one and not breaking. PR issued.
