### ISSUE TITLE
Provide major upgrade instructions for all charts and versions

### ISSUE THREAD

**Issue by nielstenboom** [allegroai/clearml-helm-charts#265]
### Is your feature request related to a problem ?

The READMEs of the charts do not provide a history of instructions on how to perform a major version upgrade.

In my case now I'd like to upgrade the `clearml` chart, we're running from `4.3.0` to the latest one but I do not know what the breaking changes are.

### Describe the solution you'd like.

It would be very nice if all READMEs keep a log of all instructions for each major version.

For example the same as the prometheus chart does it: 

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart

### Describe alternatives you've considered.

-

**Comment by valeriano-manassero** [comment]
Hi,
thanks for reporting this; we added `Major upgrade` section on README on version 6 but I still need to improve it for future versions.
Hopefully we will have a better tracking on next major release.
