### ISSUE TITLE
Example for clearml-server's env variable

### ISSUE THREAD

**Issue by pituganov** [allegroai/clearml-helm-charts#299]
I'm confused with `clearml.clientConfiguration` in values.yaml for [clearml-server deployment config](https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/templates/webserver-deployment.yaml#L86).

It would be awesome, if you could provide an example of values for it.

If I get it right, I can set custom webserver/apiserver values for "create credentials" window in settings (in `WEBSERVER__displayedServerUrls` env variable). 
By default it sets IP of my pods. But I wish I could set Ingress host value in it.

<img width="782" alt="SCR-20240619-olqd-2" src="https://github.com/allegroai/clearml-helm-charts/assets/18619869/5a07fdec-34d2-42de-bab5-01e94b8f7f20">

**Comment by valeriano-manassero** [comment]
Hi,
pls refer to README of the chart about:
* `clearml.clientConfigurationApiUrl`
* `clearml.clientConfigurationFilesUrl`

**Comment by pituganov** [comment]
But it's empty.
