### ISSUE TITLE
Helm repo not available

### ISSUE THREAD

**Issue by cedricve** [allegroai/clearml-helm-charts#309]
### Describe the bug a clear and concise description of what the bug is.

https://allegroai.github.io/clearml-helm-charts/ is not available and hence helm chart can not be executed.

### What's your helm version?

na

### What's your kubectl version?

na

### What's the chart version?

na

**Comment by cedricve** [comment]
my mistake: we should add the repo to the documentation (I used the wrong repo name to match `allegroai/clearml`)

    helm repo add allegroai https://allegroai.github.io/clearml-helm-charts/

**Comment by filippo-clearml** [comment]
I'll make sure to add a reference to the correct helm repo in the Readme for clarity!

**Comment by cedricve** [comment]
@filippo-clearml I added a PR to save you some time.

**Comment by filippo-clearml** [comment]
Ty @cedricve!
Looks good, but I'll have to change the Readme template first to keep it consistent with [Helm Docs](https://github.com/norwoodj/helm-docs)
