### ISSUE TITLE
[clearml-agent] Agent collision

### ISSUE THREAD

**Issue by cedricve** [allegroai/clearml-helm-charts#316]
### Describe the bug a clear and concise description of what the bug is.

I'm spinning up multiple clearml-agents on various clusters, and it looks like there is a conflict with the agents. I was trying to update the worker id, but that didnt help.

      - name: CLEARML_WORKER_ID
        value: "clearml-agent-k8s_gcp"

### What's your helm version?

latest

### What's your kubectl version?

1.30

### What's the chart version?

latest

**Comment by filippo-clearml** [comment]
> there is a conflict with the agents

@cedricve Could you please elaborate on that? What is the behavior you’re experiencing?

Any reference to logs, a description of your setup or screenshots of what you see in the UI would be helpful.

**Comment by cedricve** [comment]
Apologies for the brief description. So basically I deployed the same chart (with different access/secret key) on two different clusters. One cluster has access through nvidia GPU's through the nvidia operator / hami, and the other one is just a cloud based K8s cluster.

Each of the agent has their dedicated queue, and it looks like there is a collission. Workers are not showing up at the same time but swapping between the two queues (actually it thinks there is only 1 agent).

<img width="1398" alt="Screenshot 2024-08-19 at 21 06 21" src="https://github.com/user-attachments/assets/44c7c167-0daf-4c61-acc5-9031684627c2">

<img width="1398" alt="Screenshot 2024-08-19 at 21 06 55" src="https://github.com/user-attachments/assets/ef8dcc10-8295-4fff-ad82-cc5afee2eb73">

I also noticed when I start an experiment, the task will be created on both cluster (although agents are isolated through their own queue).

**Comment by filippo-clearml** [comment]
@cedricve Got it! A couple questions to help me clearing the topic:

1. Could you please share your helm values override file for both agents?
2. Also, when you started an experiment in this scenario, on which queue did you enqueue it?

**Comment by cedricve** [comment]
Thanks @filippo-clearml, so what I did is used the default values.yaml, and only modified the credentials + the queue. Other than that they are similar.

- Regarding the queue, it doesn't matter on which queue I schedule, the task will be created on each agent.

Hope this helps.

**Comment by filippo-clearml** [comment]
@cedricve what have you configured under `agentk8sglue.queue` in the two different agent values?

**Comment by filippo-clearml** [comment]
Also @cedricve, the Agent Chart defaults the `CLEARML_WORKER_ID` to be `clearmlAgent.fullname` from the template.
Can you try not defining the `CLEARML_WORKER_ID` env variable yourself and instead give the two agents a different helm release name, please?

**Comment by cedricve** [comment]
Interesting let me do that! @filippo-clearml

**Comment by cedricve** [comment]
Changing a different release name for the helm chart did worked ! :) But not really convenient to have this behaviour, I would opt for an environment name or (random name for the agent).
