### ISSUE TITLE
[clearml] File service not accessible

### ISSUE THREAD

**Issue by cedricve** [allegroai/clearml-helm-charts#318]
### Describe the bug a clear and concise description of what the bug is.

My clearml deployment works fine, the only thing I noticed is that the UI cannot load anything from the fileserver (Which continuously throws 401). This is related to following issue: https://github.com/allegroai/clearml/issues/1308

Do I need to specify some credentials some where?

    apiserver:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hostName: "api.clearml.xxx.ai"
        tlsSecretName: "api-clearml-xxx-ai-tls"
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
      additionalConfigs: 
        apiserver.conf: |
          auth {
            fixed_users {
              enabled: true
              pass_hashed: false
              users: [
                {
                  ...
                },
                {
                  ...
                }
              ]
            }
          }
    fileserver:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hostName: "files.clearml.xxx.ai"
        tlsSecretName: "files-clearml-xxx-ai-tls"
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
    webserver:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hostName: "app.clearml.xxx.ai"
        tlsSecretName: "app-clearml-xxx-ai-tls"
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
    redis:
      architecture: replication
      master:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 5Gi
          ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
          storageClass: null
      replica:
        replicaCount: 1
    mongodb:
      enabled: true
      architecture: replicaset
      replicaCount: 1
      arbiter:
        enabled: false
      pdb:
        create: true
      podAntiAffinityPreset: soft
    elasticsearch:
      replicas: 1

### What's your helm version?

latest

### What's your kubectl version?

1.29

### What's the chart version?

latest

**Comment by filippo-clearml** [comment]
Hey @cedricve, you should try configuring the `clearml.cookieDomain` values in the Helm Chart to your domain name (without any prefix) https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/values.yaml#L26

**Comment by cedricve** [comment]
Thanks @filippo-clearml for the prompt response. I gave that a try so instead of `api.clearml.domain.com` I used `clearml.domain.com`. Is that desired?

**Comment by filippo-clearml** [comment]
@cedricve that should be correct.
Could you please share your complete values file, including the `clearml` section?
Also, verify that the `CLEARML__APISERVER__AUTH__COOKIES__DOMAIN` env variable in the `clearml-apiserver` container has the same value as you set in the `clearml.cookieDomain` with a `.` (dot) in front of it.

**Comment by cedricve** [comment]
Hey @filippo-clearml, just made it work. I used the base domain `domain.com` and then cleared cache. Now working perfectly! Thanks for the tip. You can close this if you wish. Excellent support!

**Comment by filippo-clearml** [comment]
Great! Thank you!
