### ISSUE TITLE
[clearml-agent] Agent task container stops running without error and changes to failed state

### ISSUE THREAD

**Issue by cedricve** [allegroai/clearml-helm-charts#319]
### Describe the bug a clear and concise description of what the bug is.

I'm currently running an experiment in my Kubernetes cluster with the clear ml agent working which is intermittently succeeding/failing. Sometimes it completes, sometimes is just fails in the middle of a training process. As the task pod is being deleted I cannot inspect the pod what caused the failed state. Also in the web console I cannot see any reason why the task was failed.

![Screenshot 2024-08-29 at 21 36 29](https://github.com/user-attachments/assets/ede9d33f-a646-48d6-832b-5240b6c27ccc)

### What's your helm version?

latest

### What's your kubectl version?

1.29

### What's the chart version?

latest

**Comment by filippo-clearml** [comment]
Hi @cedricve, do you see any correlation between the succeeding/failing experiments?

If you try to run the exact same experiment multiple times through the same agent, will the final status toggle between Completed and Failed? Or will it consistently give the same result?

**Comment by cedricve** [comment]
The issue was related to a high number of workers, and the GPU having not enough of memory. We set workers to 0 and that made it work. Sorry for the overhead! Was not related to clearml at all but pure configuration.
