### ISSUE TITLE
[Feature Request] Custom nodeSelector and anti-affinity for all pods

### ISSUE THREAD

**Issue by stefano-cherchi** [allegroai/clearml-helm-charts#35]
Currently, when deploying ClearML with Helm, there is a single `nodeSelector` attribute in the main `clearml:` block. This parameter is propagated to all the ClearML services: apiserver, webserver, elasticsearch etc. The clearml-agents, on the other hand, have no way to specify a selector.

It would be very useful to configure node selectors and anti-affinities on each service in the values file. 

For example, I'd like to be sure that no more than one clearml-agent is running on each node of the cluster. I'd also like to be able to schedule the mongo pod an on-demand instance while keeping stateless services on a spot instance, etc.

**Comment by jkhenning** [comment]
@valeriano-manassero WDYT?

**Comment by valeriano-manassero** [comment]
On latest chart version (3.0.6) any ClearML service have a `nodeSelector` and an `affinity` section that are empty by default.
@stefano-cherchi what version are you using?

About using already existing Redis/Elastic/MongoDB avoiding to install dependency chart, I think it's a good idea I can implement.

**Comment by stefano-cherchi** [comment]
Ciao @valeriano-manassero , I just realised that I was still using the old deprecated repo `https://allegroai.github.io/clearml-server-helm/` so I was stuck at chart version `1.0.2`. 

Thank you!

**Comment by valeriano-manassero** [comment]
Ciao @stefano-cherchi :) , wdyt about the liked PR? It may be useful for you?

**Comment by stefano-cherchi** [comment]
> Ciao @stefano-cherchi :) , wdyt about the liked PR? It may be useful for you?

Makes perfect sense to me. Thanks! 

Once the MongoDB authentication [issue](https://github.com/allegroai/clearml-server/issues/86) is solved, it would also be great to have `.Values.externalServices.mongodbUser` and `.Values.externalServices.mongodbPassword`

**Comment by valeriano-manassero** [comment]
> Once the MongoDB authentication [issue](https://github.com/allegroai/clearml-server/issues/86) is solved, it would also be great to have `.Values.externalServices.mongodbUser` and `.Values.externalServices.mongodbPassword`

I totally agree, will open an issue for this so I will have a reminder for the chart when implementation is done in application.
