### ISSUE TITLE
Bind tasks logs to agents stdout

### ISSUE THREAD

**Issue by daniel-beyond** [allegroai/clearml-helm-charts#45]
Currently when running a task on an agent pod the task logs are written locally to log files at 
/tmp/.clearml_agent_out.<random num>.txt
but not streamed to stdout.

Is there a way to bind those logs to the host stdout so that the logs are visible when running: "kubectl logs <pod name>" which will help with centralize logging as well.

Thanks!

**Comment by jkhenning** [comment]
Hi @daniel-beyond ,

Thanks for this issue. We'll investigate it - it might require a complementary feature in ClearML Agent as well.

**Comment by valeriano-manassero** [comment]
> it might require a complementary feature in ClearML Agent as well.

I tried some workaround without success; maybe you are right 😁

**Comment by jkhenning** [comment]
@valeriano-manassero I believe that starting the damon agent with `--foreground` will cause all of the output and logs to be dumped to stdout as well - which might be just what's needed for this 🙂

**Comment by valeriano-manassero** [comment]
ClearML chart 3.2.2 published and this issue should be solved, feel free to open new one if there are still issues.
