### ISSUE TITLE
Allowing auth secrets to be optional 

### ISSUE THREAD

**Issue by srp-31** [allegroai/clearml-helm-charts#60]
Hi there.
[Here](https://github.com/allegroai/clearml-helm-charts/blob/e16060f2ad9f7075531e132ad9f8155dc5e7870f/charts/clearml/templates/deployment-apiserver.yaml#L80)
the auth secretes are loaded into the environment variables from the secret. I feel that this is a bit restircting. I would like to set the environment varibales directly in the values file (referreing a to a Hashicrop vault secret). Can we have something like
 
 {{- if .Values.secret}}
           - name: CLEARML__SECURE__HTTP__SESSION_SECRET__APISERVER
            valueFrom:
              secretKeyRef:
                name: clearml-conf
                key: http_session
.
.
.
.           
 {{- else }}
 
 If this makes sense I will be happy to create a pull request sometime later this week or early next week ;)

**Comment by valeriano-manassero** [comment]
If the implementation you have in mind is not going to break backward compatibility (and it shouldn't from what I can see from your proposal) I think we are good. I will wait for your PR referring this issue and let's see how we can integrate it.
Ty!

**Comment by Shm013** [comment]
I think it will be great to add existing secret option for all secret variables such as:

- HTTP_SESSION_KEY
- AUTH_TOKEN_KEY
- API_ACCESS_KEY
- API_SECRET_KEY
- TESTS_ACCESS_KEY
- TESTS_SECRET_KEY

**Comment by jkhenning** [comment]
Hi @Shm013, would you like to create a PR?

**Comment by Shm013** [comment]
Hi @jkhenning, I'm going to do this next week.
