### ISSUE TITLE
K8sglue agent is broken on 3.10.0

### ISSUE THREAD

**Issue by nielstenboom** [allegroai/clearml-helm-charts#64]
I'm afraid that on the latest version the k8sagent is broken when you set any tolerations or nodeselectors. The following is from the log of the agent:
```
error: error validating "/tmp/clearml_k8stmpl_5shxhzm4.yml": error validating data: 
[ValidationError(Pod.spec.containers[0]): unknown field "fleet" in io.k8s.api.core.v1.Container, 
ValidationError(Pod.spec.containers[0]): unknown field "tolerations" in io.k8s.api.core.v1.Container]; if you choose to 
ignore these errors, turn validation off with --validate=false
```

Used values (this worked on earlier versions):
```yaml
agentk8sglue:
  # rest of vars ...
  podTemplate:
      resources:
        limits:
          nvidia.com/gpu: 1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: Exists
          effect: "NoSchedule"
        - key: "spot"
          operator: Exists
          effect: "NoSchedule"
        - key: "gpu"
          operator: Exists
          effect: "NoSchedule"
      nodeSelector:
        fleet: gpus
```

**Comment by jkhenning** [comment]
@nielstenboom the k8s glue is actually not related to the server version, and is part of the clearml-agent. The only recent change in the k8s was actually made about 10min ago, so I'm not sure it is related... Perhaps your issue has something to do with the k8s cluster setup?

**Comment by jkhenning** [comment]
@nielstenboom I just realized I might be wrong, I'll defer to @valeriano-manassero to answer 🙂

**Comment by valeriano-manassero** [comment]
I can reproduce the issue. I'll work on it in next couple of days; hopefully I'll have good news soon.

**Comment by nielstenboom** [comment]
Thanks guys!

I think I actually see the issue @valeriano-manassero, the indentation here: https://github.com/allegroai/clearml-helm-charts/pull/59/files#diff-7ae0b2e2408c01f13047490661f93fa0fc317651e7427c305b72cadd93df8a8fR46-R56 
Is slightly off, it's too indented.

**Comment by valeriano-manassero** [comment]
If you're in hurry pls try to create a PR. If this is not possible I can check tomorrow!

**Comment by nielstenboom** [comment]
It's not urgent but I'll create a PR! 😄
