### ISSUE TITLE
Add clearml-serving helm chart

### ISSUE THREAD

**Issue by stefano-cherchi** [allegroai/clearml-helm-charts#67]
Opening this issue, according to the project's Contributing Guidelines, to provide a reference in the following PR.

The pull request will contain a Helm chart to deploy ClearML Model-Serving Orchestration and Repository Solution on Kubernetes.

The chart has been tested on a ClearML Server deployment released with version 3.8.0 of the Helm chart published in this repository.

**Comment by valeriano-manassero** [comment]
Hi @stefano-cherchi and thank you for this;
my suggestion is to fork this repo on your user and then issue a PR from there.
Basically you can just add a new folder with the entire Chart unser `charts` folder.

In this way we will have at least one CI triggered and we can discuss further steps together.
