### ISSUE TITLE
Helm chart does not work with openshift

### ISSUE THREAD

**Issue by Legit55555** [allegroai/clearml-helm-charts#68]
i've tried setting up a clearml application on openshift using your chart but the pods cannot go up as they are trying to write to files 
and directories that aren't open to non root users. this becomes a problem on openshift as it does not allow containers to run with as root but instead runs them as random users from the root group.

**Comment by valeriano-manassero** [comment]
I don't have an open shift installation to test atm.

Can you pls point me on a working configuration for you pls?

**Comment by valeriano-manassero** [comment]
A section containing specific platform configs was added here: https://github.com/allegroai/clearml-helm-charts/tree/main/platform-specific-configs/

It would be interesting to do something similar to Tanzu, if anyone have any clue on what should be done would be welcome to open a PR.
