### ISSUE TITLE
Add extraEnvs to agentGroups templates in clearml char templates

### ISSUE THREAD

**Issue by lucacerone** [allegroai/clearml-helm-charts#75]
The current implementation in [deployment-agent.yaml](https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml/templates/deployment-agent.yaml) doesn't allow to set extra environment
variables in the agents defined under the `agentGroups` in [values.yaml](https://github.com/allegroai/clearml-helm-charts/blob/9cf2868738927efb218d498e26caadcfe530f948/charts/clearml/values.yaml#L258).

One problem with this is that we can't define proxies and the agent deployment fail because it can't fetch
the required resources (e.g. ubuntu packages etc).

**Comment by valeriano-manassero** [comment]
Hi @lucacerone , I can check implementation about this in some day. Sorry but I'm a bit busy atm. If you have a PR in the meanwhile you are welcome 😃, if not I can cook something for next week.

**Comment by lucacerone** [comment]
Thanks @valeriano-manassero, I gave it a shot. I have a doubt whether I should add it to the k8s-agent deployment (for k8s glue) too.  And I'm not sure whether I should have bumped the version or that's something that happens automatically when you merge. Let me know of any change that might be needed!

**Comment by valeriano-manassero** [comment]
PR merged and chart 3.10.4 released. Ty very much for your contribution!

**Comment by lucacerone** [comment]
Thank you for your help with it!
