### ISSUE TITLE
Artifacthub.io account

### ISSUE THREAD

**Issue by valeriano-manassero** [allegroai/clearml-helm-charts#8]
We should sing up for a free account on Artifcthub.io so we can get the code to enable automatic publishing of the chart.
Today Artifacthub.io is widely used as a search engine for charts and only my one (that I will deprecate soon in favour of this one) is listed for ClearML.
Moreover we can ask for `official` tag :)

**Comment by jkhenning** [comment]
Sounds good - I'll create a ClearML account 🙂

**Comment by valeriano-manassero** [comment]
Repo is now listed in artifacthub.io :

https://artifacthub.io/packages/helm/allegroai/clearml

According to https://artifacthub.io/docs/topics/repositories/#official-status @jkhenning can you pls open an issue using this template https://github.com/artifacthub/hub/issues/new?assignees=&labels=official+status+request&template=official-status-request.md&title=%5BOFFICIAL%5D+Your+repository+or+project+name to get Official status?

I think having Official badge is a good thing 😄

**Comment by jkhenning** [comment]
@valeriano-manassero just to make sure (since I don't have any experience with it), I assume the following?

title: [OFFICIAL] https://artifacthub.io/packages/helm/allegroai/clearml
Repository name (in artifacthub.io): ClearML
Project URL: https://clear.ml
Source code URL (if available): https://allegroai.github.io/clearml-helm-charts

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero just to make sure (since I don't have any experience with it), I assume the following?
> 
> 
> 
> title: [OFFICIAL] https://artifacthub.io/packages/helm/allegroai/clearml
> 
> Repository name (in artifacthub.io): ClearML
> 
> Project URL: https://clear.ml
> 
> Source code URL (if available): https://allegroai.github.io/clearml-helm-charts
> 
> 

lgtm

**Comment by jkhenning** [comment]
Submitted: https://github.com/artifacthub/hub/issues/1457

**Comment by jkhenning** [comment]
Done 🙂
