### ISSUE TITLE
Allow to install multiple agents in the same K8S cluster

### ISSUE THREAD

**Issue by Shm013** [allegroai/clearml-helm-charts#91]
I want to install two agents - first for CPU and second for GPU payload, but I have conflict during installation because of resource names.

I want to use a single namespace for both agents, because I have already configured ingress, container registry and configures in this namespace.

I already made tweaks for my own. I had use `agentk8sglue.referenceName` in all resource name. For example:

```
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
+  name: {{ include "agentk8sglue.referenceName" . }}-pods-access
-  name: k8sagent-pods-access
```

How do you think is it good feature, or I do wrong?

**Comment by valeriano-manassero** [comment]
I think this is a good idea, I'm going to cook something soon.

**Comment by valeriano-manassero** [comment]
Chart release 1.2.0 should enable you to have multiple Agents now.
