### ISSUE TITLE
clearml-agent helm chart: referenceName not applied

### ISSUE THREAD

**Issue by lucacerone** [allegroai/clearml-helm-charts#96]
From my understanding in #92 a "referenceName" parameter was added to the helm chart for clearml agent to be able to deploy several agent-glues in the same namespace without clashing names.

In the values.yaml, however, there is no "referenceName" parameter, so that when deploying multiple agents, a naming conflict arise.

**Comment by valeriano-manassero** [comment]
referenceName is defined as helper function here: https://github.com/allegroai/clearml-helm-charts/blob/main/charts/clearml-agent/templates/_helpers.tpl#L56

Basically we are using Chart Name to identify resources; maybe we should move to Release.Name so many instances can coexist. I can try to cook something in next days.

**Comment by valeriano-manassero** [comment]
@lucacerone can you pls try the change related the PR pls?

**Comment by lucacerone** [comment]
@valeriano-manassero first of all thanks a lot!
I'd be happy to try, but I don't know how to point the dependencies in our helm chart to a github branch.

**Comment by valeriano-manassero** [comment]
You can test chart version 1.2.3 that is now released.
