### ISSUE TITLE
Let custom annotations in Secrets metadata.

### ISSUE THREAD

**Issue by lucacerone** [allegroai/clearml-helm-charts#99]
Currently Secrets for "clearml" and "clearml-agent" charts are created from "values.yaml" files.

We'd like to annotate the secrets so that we can get the values of the secrets from Vault.

**Comment by jkhenning** [comment]
@lucacerone sounds interesting - care to suggest a PR? 🙂

**Comment by lucacerone** [comment]
@jkhenning I have an half baked solution. But didn't have the time to test it. I'll open a PR this or next week.
